type MyEmployee = {
  firstName: string;
  _id?: string;
  lastName: string;
  emailAddress: string;
  phoneNumber: string;
  emergencyPhoneNumber: string;
  bankName: string;
  bankAccountNumber: number;
  accountName: string;
  physicalAddress: string;
  gender: string;
  nextOfKinFullName: string;
  nextOfKinPhoneNumber: string;
  nextOfKinRelationship: string;
  employmentRole: string;
  employmentStartDate: string;
  dateOfBirth: string;
  educationalLevel: string;
  _id: string;
};
